const fs = require('fs');

const translations = {
  en: {
    DashboardProfile: {
      title: "Profile & Security",
      desc: "Manage your account information and password.",
      change_password: "Change Password",
      pwd_mismatch: "New passwords do not match.",
      pwd_length: "New password must be at least 6 characters.",
      pwd_success: "Password successfully updated.",
      pwd_error: "Error updating password.",
      current_pwd: "Current password",
      new_pwd: "New password",
      confirm_pwd: "Confirm new password",
      saving: "Saving...",
      update_btn: "Update Password"
    },
    DashboardAccounts: {
      title: "MT5 Accounts",
      desc: "Manage your MetaTrader 5 accounts linked to your licenses.",
      add_new: "Add New Account",
      err_adding: "Error adding account",
      account_number: "MT5 Account Number",
      broker_name: "Broker Name",
      broker_note: "Currently, we exclusively support Fusion Markets.",
      linking: "Linking...",
      link_btn: "Link Account",
      linked: "Linked Accounts",
      loading: "Loading accounts...",
      no_accounts: "No MT5 accounts linked yet.",
      delete: "Delete",
      confirm_delete: "Are you sure you want to delete this account? Any associated licenses will be detached."
    },
    DashboardBilling: {
      title: "Billing & Checkout",
      desc: "Upgrade your plan to increase your Lot Limit and unlock premium features.",
      err_load: "Failed to load plans",
      err_pay: "Error initiating payment",
      weekly: "Weekly",
      monthly: "Monthly",
      six_months: "6 Months",
      yearly: "Yearly",
      popular: "Popular",
      lot_limit: "Lot Limit:",
      auto_trade: "Full automated trading",
      support: "Premium Support",
      subscribe: "Subscribe",
      subscribing: "..."
    },
    DashboardDownloads: {
      title: "Downloads",
      desc: "Download the latest version of your Expert Advisor.",
      err_load: "Error loading data.",
      success_download: "Download started! If nothing happens, check your downloads.",
      err_download: "Error generating link. Verify you have an active license.",
      active_license: "Active License",
      no_license: "No License",
      plan: "Plan :",
      expires: "Expires on :",
      generating: "Generating link...",
      download_btn: "Download EA (.ex5)",
      buy_btn: "Buy a license",
      no_bots: "No bots available.",
      guide_title: "Quick Installation Guide",
      step1: "Download the .ex5 file above.",
      step2: "Open MetaTrader 5 and go to File → Open Data Folder.",
      step3: "Place the file in the MQL5/Experts folder.",
      step4: "Go to Tools → Options → Expert Advisors and allow WebRequest for your license URL.",
      step5: "Drag the EA onto a XAU/USD chart and enable automated trading. 🚀"
    }
  },
  fr: {
    DashboardProfile: {
      title: "Profil & Sécurité",
      desc: "Gérez vos informations de compte et votre mot de passe.",
      change_password: "Changer de mot de passe",
      pwd_mismatch: "Les nouveaux mots de passe ne correspondent pas.",
      pwd_length: "Le nouveau mot de passe doit contenir au moins 6 caractères.",
      pwd_success: "Mot de passe modifié avec succès.",
      pwd_error: "Erreur lors de la modification du mot de passe.",
      current_pwd: "Mot de passe actuel",
      new_pwd: "Nouveau mot de passe",
      confirm_pwd: "Confirmer le nouveau mot de passe",
      saving: "Enregistrement...",
      update_btn: "Mettre à jour le mot de passe"
    },
    DashboardAccounts: {
      title: "Comptes MT5",
      desc: "Gérez vos comptes MetaTrader 5 liés à vos licences.",
      add_new: "Ajouter un nouveau compte",
      err_adding: "Erreur lors de l'ajout du compte",
      account_number: "Numéro de compte MT5",
      broker_name: "Nom du courtier",
      broker_note: "Actuellement, nous supportons exclusivement Fusion Markets.",
      linking: "Liaison...",
      link_btn: "Lier le compte",
      linked: "Comptes liés",
      loading: "Chargement des comptes...",
      no_accounts: "Aucun compte MT5 lié pour le moment.",
      delete: "Supprimer",
      confirm_delete: "Êtes-vous sûr de vouloir supprimer ce compte ? Toutes les licences associées seront détachées."
    },
    DashboardBilling: {
      title: "Facturation & Paiement",
      desc: "Améliorez votre plan pour augmenter votre limite de lot et débloquer des fonctionnalités premium.",
      err_load: "Échec du chargement des plans",
      err_pay: "Erreur lors de l'initiation du paiement",
      weekly: "Hebdomadaire",
      monthly: "Mensuel",
      six_months: "6 Mois",
      yearly: "Annuel",
      popular: "Populaire",
      lot_limit: "Limite de lot :",
      auto_trade: "Trading 100% automatisé",
      support: "Support Premium",
      subscribe: "S'abonner",
      subscribing: "..."
    },
    DashboardDownloads: {
      title: "Téléchargements",
      desc: "Téléchargez la dernière version de votre Expert Advisor.",
      err_load: "Erreur lors du chargement des données.",
      success_download: "Téléchargement lancé ! Si rien ne se passe, vérifiez vos téléchargements.",
      err_download: "Erreur lors de la génération du lien. Vérifiez que vous avez une licence active.",
      active_license: "Licence Active",
      no_license: "Pas de licence",
      plan: "Plan :",
      expires: "Expire le :",
      generating: "Génération du lien...",
      download_btn: "Télécharger l'EA (.ex5)",
      buy_btn: "Acheter une licence",
      no_bots: "Aucun robot disponible.",
      guide_title: "Guide d'installation rapide",
      step1: "Téléchargez le fichier .ex5 ci-dessus.",
      step2: "Ouvrez MetaTrader 5 et allez dans Fichier → Ouvrir le dossier de données.",
      step3: "Placez le fichier dans le dossier MQL5/Experts.",
      step4: "Allez dans Outils → Options → Expert Advisors et autorisez le WebRequest pour l'URL de votre licence.",
      step5: "Glissez l'EA sur un graphique XAU/USD et activez le trading automatique. 🚀"
    }
  },
  es: {
    DashboardProfile: {
      title: "Perfil y Seguridad",
      desc: "Gestione la información de su cuenta y contraseña.",
      change_password: "Cambiar contraseña",
      pwd_mismatch: "Las nuevas contraseñas no coinciden.",
      pwd_length: "La nueva contraseña debe tener al menos 6 caracteres.",
      pwd_success: "Contraseña modificada con éxito.",
      pwd_error: "Error al cambiar la contraseña.",
      current_pwd: "Contraseña actual",
      new_pwd: "Nueva contraseña",
      confirm_pwd: "Confirmar nueva contraseña",
      saving: "Guardando...",
      update_btn: "Actualizar contraseña"
    },
    DashboardAccounts: {
      title: "Cuentas MT5",
      desc: "Gestione sus cuentas MetaTrader 5 vinculadas a sus licencias.",
      add_new: "Añadir nueva cuenta",
      err_adding: "Error al añadir la cuenta",
      account_number: "Número de cuenta MT5",
      broker_name: "Nombre del bróker",
      broker_note: "Actualmente, solo admitimos Fusion Markets.",
      linking: "Vinculando...",
      link_btn: "Vincular cuenta",
      linked: "Cuentas vinculadas",
      loading: "Cargando cuentas...",
      no_accounts: "Aún no hay cuentas MT5 vinculadas.",
      delete: "Eliminar",
      confirm_delete: "¿Está seguro de querer eliminar esta cuenta? Todas las licencias asociadas se desvincularán."
    },
    DashboardBilling: {
      title: "Facturación y Pago",
      desc: "Actualice su plan para aumentar su límite de lote y desbloquear funciones premium.",
      err_load: "Error al cargar los planes",
      err_pay: "Error al iniciar el pago",
      weekly: "Semanal",
      monthly: "Mensual",
      six_months: "6 Meses",
      yearly: "Anual",
      popular: "Popular",
      lot_limit: "Límite de Lote:",
      auto_trade: "Comercio totalmente automatizado",
      support: "Soporte Premium",
      subscribe: "Suscribirse",
      subscribing: "..."
    },
    DashboardDownloads: {
      title: "Descargas",
      desc: "Descargue la última versión de su Expert Advisor.",
      err_load: "Error al cargar los datos.",
      success_download: "¡Descarga iniciada! Si no ocurre nada, revise sus descargas.",
      err_download: "Error al generar el enlace. Verifique que tiene una licencia activa.",
      active_license: "Licencia Activa",
      no_license: "Sin licencia",
      plan: "Plan :",
      expires: "Expira el :",
      generating: "Generando enlace...",
      download_btn: "Descargar EA (.ex5)",
      buy_btn: "Comprar licencia",
      no_bots: "No hay robots disponibles.",
      guide_title: "Guía de instalación rápida",
      step1: "Descargue el archivo .ex5 de arriba.",
      step2: "Abra MetaTrader 5 y vaya a Archivo → Abrir carpeta de datos.",
      step3: "Coloque el archivo en la carpeta MQL5/Experts.",
      step4: "Vaya a Herramientas → Opciones → Asesores Expertos y permita WebRequest para la URL de su licencia.",
      step5: "Arrastre el EA a un gráfico XAU/USD y active el trading automático. 🚀"
    }
  },
  pt: {
    DashboardProfile: {
      title: "Perfil e Segurança",
      desc: "Gerencie as informações da sua conta e senha.",
      change_password: "Mudar Senha",
      pwd_mismatch: "As novas senhas não coincidem.",
      pwd_length: "A nova senha deve ter pelo menos 6 caracteres.",
      pwd_success: "Senha atualizada com sucesso.",
      pwd_error: "Erro ao atualizar a senha.",
      current_pwd: "Senha atual",
      new_pwd: "Nova senha",
      confirm_pwd: "Confirmar nova senha",
      saving: "Salvando...",
      update_btn: "Atualizar Senha"
    },
    DashboardAccounts: {
      title: "Contas MT5",
      desc: "Gerencie suas contas MetaTrader 5 vinculadas às suas licenças.",
      add_new: "Adicionar Nova Conta",
      err_adding: "Erro ao adicionar conta",
      account_number: "Número da Conta MT5",
      broker_name: "Nome da Corretora",
      broker_note: "Atualmente, suportamos exclusivamente a Fusion Markets.",
      linking: "Vinculando...",
      link_btn: "Vincular Conta",
      linked: "Contas Vinculadas",
      loading: "Carregando contas...",
      no_accounts: "Nenhuma conta MT5 vinculada ainda.",
      delete: "Excluir",
      confirm_delete: "Tem certeza que deseja excluir esta conta? Quaisquer licenças associadas serão desvinculadas."
    },
    DashboardBilling: {
      title: "Faturamento e Check-out",
      desc: "Faça um upgrade no seu plano para aumentar o limite do seu Lote e desbloquear recursos premium.",
      err_load: "Falha ao carregar os planos",
      err_pay: "Erro ao iniciar o pagamento",
      weekly: "Semanal",
      monthly: "Mensal",
      six_months: "6 Meses",
      yearly: "Anual",
      popular: "Popular",
      lot_limit: "Limite de Lote:",
      auto_trade: "Negociação 100% automatizada",
      support: "Suporte Premium",
      subscribe: "Assinar",
      subscribing: "..."
    },
    DashboardDownloads: {
      title: "Downloads",
      desc: "Baixe a versão mais recente do seu Expert Advisor.",
      err_load: "Erro ao carregar dados.",
      success_download: "Download iniciado! Se nada acontecer, verifique seus downloads.",
      err_download: "Erro ao gerar o link. Verifique se você tem uma licença ativa.",
      active_license: "Licença Ativa",
      no_license: "Sem licença",
      plan: "Plano :",
      expires: "Expira em :",
      generating: "Gerando link...",
      download_btn: "Baixar EA (.ex5)",
      buy_btn: "Comprar licença",
      no_bots: "Nenhum robô disponível.",
      guide_title: "Guia de instalação rápida",
      step1: "Baixe o arquivo .ex5 acima.",
      step2: "Abra o MetaTrader 5 e vá em Arquivo → Abrir pasta de dados.",
      step3: "Coloque o arquivo na pasta MQL5/Experts.",
      step4: "Vá em Ferramentas → Opções → Expert Advisors e permita WebRequest para a URL da sua licença.",
      step5: "Arraste o EA para um gráfico XAU/USD e ative a negociação automática. 🚀"
    }
  },
  ar: {
    DashboardProfile: {
      title: "الملف الشخصي والأمان",
      desc: "إدارة معلومات حسابك وكلمة المرور.",
      change_password: "تغيير كلمة المرور",
      pwd_mismatch: "كلمات المرور الجديدة غير متطابقة.",
      pwd_length: "يجب أن تتكون كلمة المرور الجديدة من 6 أحرف على الأقل.",
      pwd_success: "تم تحديث كلمة المرور بنجاح.",
      pwd_error: "حدث خطأ أثناء تحديث كلمة المرور.",
      current_pwd: "كلمة المرور الحالية",
      new_pwd: "كلمة المرور الجديدة",
      confirm_pwd: "تأكيد كلمة المرور الجديدة",
      saving: "جاري الحفظ...",
      update_btn: "تحديث كلمة المرور"
    },
    DashboardAccounts: {
      title: "حسابات MT5",
      desc: "إدارة حسابات ميتاتريدر 5 المرتبطة بتراخيصك.",
      add_new: "إضافة حساب جديد",
      err_adding: "خطأ في إضافة الحساب",
      account_number: "رقم حساب MT5",
      broker_name: "اسم الوسيط",
      broker_note: "حاليًا، ندعم حصريًا Fusion Markets.",
      linking: "جاري الربط...",
      link_btn: "ربط الحساب",
      linked: "الحسابات المرتبطة",
      loading: "جاري تحميل الحسابات...",
      no_accounts: "لا توجد حسابات MT5 مرتبطة بعد.",
      delete: "حذف",
      confirm_delete: "هل أنت متأكد أنك تريد حذف هذا الحساب؟ سيتم فصل أي تراخيص مرتبطة."
    },
    DashboardBilling: {
      title: "الفواتير والدفع",
      desc: "قم بترقية خطتك لزيادة حد اللوت الخاص بك وفتح الميزات المميزة.",
      err_load: "فشل تحميل الخطط",
      err_pay: "حدث خطأ أثناء بدء الدفع",
      weekly: "أسبوعي",
      monthly: "شهري",
      six_months: "6 أشهر",
      yearly: "سنوي",
      popular: "شائع",
      lot_limit: "حد اللوت:",
      auto_trade: "تداول آلي بالكامل",
      support: "دعم متميز",
      subscribe: "اشتراك",
      subscribing: "..."
    },
    DashboardDownloads: {
      title: "التنزيلات",
      desc: "قم بتنزيل أحدث إصدار من المستشار الخبير الخاص بك.",
      err_load: "حدث خطأ أثناء تحميل البيانات.",
      success_download: "بدأ التنزيل! إذا لم يحدث شيء، تحقق من التنزيلات.",
      err_download: "خطأ في إنشاء الرابط. تحقق من وجود ترخيص نشط.",
      active_license: "ترخيص نشط",
      no_license: "لا يوجد ترخيص",
      plan: "الخطة :",
      expires: "ينتهي في :",
      generating: "جاري إنشاء الرابط...",
      download_btn: "تنزيل EA (.ex5)",
      buy_btn: "شراء ترخيص",
      no_bots: "لا توجد روبوتات متاحة.",
      guide_title: "دليل التثبيت السريع",
      step1: "قم بتنزيل ملف .ex5 أعلاه.",
      step2: "افتح ميتاتريدر 5 وانتقل إلى ملف → فتح مجلد البيانات.",
      step3: "ضع الملف في مجلد MQL5/Experts.",
      step4: "انتقل إلى أدوات → خيارات → المستشارون الخبراء واسمح بـ WebRequest لعنوان URL للترخيص الخاص بك.",
      step5: "اسحب EA إلى مخطط XAU/USD وقم بتمكين التداول الآلي. 🚀"
    }
  }
};

for (const [lang, obj] of Object.entries(translations)) {
  const filePath = `c:/DEV/gold-trading-bot/messages/${lang}.json`;
  if (fs.existsSync(filePath)) {
    const data = JSON.parse(fs.readFileSync(filePath, 'utf8'));
    Object.assign(data, obj);
    fs.writeFileSync(filePath, JSON.stringify(data, null, 2), 'utf8');
  }
}
